prompt Importing table DWH_DIM_PROCESSES...
set feedback off
set define off
insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('US2', 'Auth users data', 0, 'CORE', 'DWH', 'M', 'DWH4BI', 'MGMT_MRR_AUTH_USERS', '03-JUL-22 11.45.46.000000 AM', '03-APR-22 09.16.51.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('VC1', 'Voice center calls', 1, 'Telephony', 'DWH', 'H', 'Voice center API', 'extsrc.VC_CALLS', '03-JUL-22 11.45.01.000000 AM', '03-APR-22 12.42.01.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SL1', 'Solitics ETL', 1, 'Marketing', 'DWH', 'H', 'DWH & Production', 'Solitics shared database MySQL', '03-JUL-22 10.45.15.000000 AM', '02-JUN-22 10.49.29.000000 AM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('LS1', 'Leads scoring engine', 1, 'Scoring model', 'DWH', 'W', 'DWH', 'DWH tables', '02-AUG-21 07.04.42.000000 PM', '26-JUL-21 06.15.01.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FTR1', 'FTR data', 1, 'CORE', 'DWH', 'M', 'Production', 'MGMT_MRR_FTR', '03-JUL-22 11.45.00.000000 AM', '25-APR-22 01.58.40.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('KYC3', 'KYC performance dashboard', 1, 'COMPLIANCE', 'DWH4BI', 'H', 'DWH4BI', 'DWH_REP_KYC_PERFORMANCE, DWH_FACT_KYC_APPROVAL_TIME', '03-JUL-22 09.17.46.000000 AM', '24-MAY-22 08.59.41.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('RPT1', 'Reports send automation', 1, 'REPROTS', 'DWH', 'M', 'DWH and other systems', 'Emailing files to employees', '03-JUL-22 11.40.00.000000 AM', '15-DEC-21 05.42.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('POP1', 'User popup messages data', 1, 'PRODUCT', 'DWH', 'H', 'DWH4BI', 'DWH_FACT_USER_POPUP_MESSAGES', '03-JUL-22 11.08.07.000000 AM', '23-DEC-20 11.08.01.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TRG1', 'Users target audience definitions', 0, 'PRODUCT', 'DWH', 'H', 'DWH4BI', 'DWH_FACT_USER_TARGET_AUDIENCES', '14-MAY-22 09.03.10.000000 PM', '16-MAY-21 04.05.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEP1', 'Deposits for users activation month', 0, 'Deposits', 'DWH', 'H', 'DWH4BI', 'DWH_FACT_DEPOSITS_ACTIVATION_MONTH', '23-JUN-20 10.54.32.000000 PM', '12-AUG-18 09.51.27.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CZ1', 'Czech regulation reports - old obsolete process', 0, 'Regulation', 'DWH', 'D', 'Production', 'Excel files via email', '02-OCT-18 01.35.21.000000 AM', '14-AUG-18 09.34.24.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CZ2', 'Czech regulation daily reports', 1, 'Regulation', 'DWH', 'D', 'Production', 'Excel files via email', '06-APR-22 12.06.12.000000 AM', '16-MAY-21 04.12.07.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TRD1', 'Trades/Positiond related data', 1, 'Core', 'DWH', 'M', 'Production', 'MGMT_MRR_TRD_DEALS , MGMT_FACT_DEALS', '03-JUL-22 11.45.08.000000 AM', '01-JUL-22 05.48.05.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('ORD1', 'Orders and orders deals', 0, 'Core', 'DWH', 'M', 'Production TRD_ORDERS and TRD_ORDERS_DELAS', 'dwh4bi.MGMT_MRR_ORDERS , dwh4bi.MGMT_MRR_ORDERS_DEALS', '20-APR-22 08.27.07.000000 AM', '16-DEC-21 12.02.04.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AD1', 'Google adwords data', 1, 'Marketing', 'DWH', 'M', 'DWH4BI', 'MGMT_FACT_ADWORDS_AD,MGMT_FACT_ADWORDS_KEYWORD,MGMT_FACT_ADWORDS_PLACEMENT', '03-JUL-22 11.00.49.000000 AM', '03-APR-22 01.50.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('UC1', null, 1, 'BI', 'DWH_LEARN', 'M', 'DWH4BI', null, '24-MAY-22 04.19.13.000000 AM', '05-APR-22 07.11.09.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('US3', 'Users daily aggregations', 1, 'CORE', 'DWH', 'M', 'DWH4BI', 'MGMT_FACT_USERS_DAY_AG', '03-JUL-22 11.38.08.000000 AM', '30-JUN-22 09.16.41.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('KYC1', 'Various KYC related tables ETL', 1, 'COMPLIANCE', 'DWH', 'M', 'DWH4BI', 'MGMT_FACT_KYC_HISTORY_CHANGE,MGMT_FACT_KYC_DEP_LEVEL,MGMT_FACT_KYC_DAY_AG', '03-JUL-22 10.53.19.000000 AM', '06-JUN-22 03.23.00.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('IB1', 'Data for IBs', 0, 'IBs', 'DWH', 'M', 'DWH4BI', 'FACT_IB_DEALS_COSTS,MGMT_FACT_IB_USERS_DAILY,MGMT_FACT_IB_DAILY_COSTS,MGMT_FACT_IB_MONTHLY_SUMMARY', '17-FEB-21 08.48.02.000000 AM', '07-MAY-20 12.00.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('USG1', 'Platform various usage data', 0, 'CORE', 'DWH', 'M', 'DWH4BI', 'MOBILE_USER_SESSION,WEB_USER_SESSION,MGMT_FACT_USERS_MOBILE,MGMT_FACT_PRICE_ALERTS,MGMT_FACT_APP_LOADING', '08-FEB-21 06.19.09.000000 AM', '16-FEB-21 04.58.34.000000 PM', 'E', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AC1', 'ACCT_ACCOUNTS table refresh ETL', 1, 'CORE', 'DWH', 'M', 'Paragonex production', 'MGMT_MRR_ACCT_ACCOUNTS', '03-JUL-22 11.42.04.000000 AM', '03-APR-22 12.59.00.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DOC1', 'KYC documents data', 1, 'KYC', 'DWH', 'M', 'Paragonex production KYC', 'MGMT_MRR_KYC_DOCS', '03-JUL-22 10.40.04.000000 AM', '18-DEC-21 03.17.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('GA1', 'Google Analytics ETL', 1, null, 'DWH4BI', 'D', 'Google Analytics', 'extsrc', '03-JUL-22 12.00.38.000000 AM', '15-DEC-21 12.00.45.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEAL3', 'Dealing room real time dashboard', 1, 'DEALING', 'DWH', 'M', 'DWH4BI', 'Tableau dashboard', '03-JUL-22 11.45.23.000000 AM', '23-JUN-22 01.48.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SLV1', 'Silverpop Data Download', 1, 'Marketing', 'EXTSRC', 'H', 'Acoustic (Silverpop)', 'EXTSRC.SLV_EVENTS', '15-DEC-21 08.05.11.000000 AM', '15-DEC-21 07.04.52.000000 AM', 'R', to_date('05-05-2021 11:48:55', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DUP1', 'Duplicate users/leads', 1, null, 'DWH', 'D', 'DWH4BI', 'DWH_FACT_DUPLICATE_USERS', '03-JUL-22 03.31.27.000000 AM', '16-DEC-21 03.13.01.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CMP1', 'compliance data', 0, 'COMPLIANCE', 'DWH', null, null, null, '03-JUL-22 09.40.51.000000 AM', '01-JUN-22 04.59.01.000000 AM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FSQ2', 'File system queue from platform using Talend', 1, 'FILE SYSTEM DATA', 'DWH', 'H', 'Paragonex production', 'EXTERNAL TABLES IN DWH', '03-JUL-22 11.45.04.000000 AM', '12-JUN-22 11.24.19.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DLR1', 'Dialer data', 1, 'Telephony', 'DWH', 'H', 'Dialer data in production', 'Dialer data tables', '03-JUL-22 11.41.00.000000 AM', '03-APR-22 01.00.00.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MGMT1', 'Main fact tables', 0, 'CORE', 'DWH', 'H', 'Paragonex production', 'MGMT layer tables in DWH', '04-FEB-19 01.14.00.000000 PM', '29-JAN-19 05.44.52.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DIM1', 'Common dimension tables', 1, 'CORE', 'DWH', 'H', 'Paragonex production', 'DIM layer tables in DWH', '03-JUL-22 11.30.21.000000 AM', '06-JUN-22 01.18.00.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MRR1', 'Small MRR tables', 0, 'CORE', 'DWH', 'H', 'Paragonex production', 'MRR layer tables in DWH', '30-JAN-19 10.43.02.000000 AM', '01-SEP-18 09.19.03.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('LP1', 'Limiting positions reports', 0, 'Trading', 'DWH', 'D', 'DWH4BI', 'DWH_REP_FAILED_OPEN_POSITIONS', '14-MAY-20 08.01.01.000000 AM', '11-MAR-18 04.12.32.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MRK2', 'New marketing dashboard ETL', 1, 'MARKETING', 'DWH', 'M', 'DWH4BI', 'DWH_REP_MARKETING_DASHBOARD', '03-JUL-22 06.59.57.000000 AM', '08-JUN-22 11.03.34.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEC1', 'Personal user info decription', 1, 'Users', 'DWH', 'D', 'Paragonex production', 'DWH_USERS_DECRYPTED', null, null, 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('USR1', 'New users ETL', 1, 'CORE', 'DWH', 'M', 'Paragonex', 'DWH_FACT_USERS', '03-JUL-22 11.45.34.000000 AM', '30-MAY-22 06.15.58.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('GTL1', 'GetLinked API Python', 1, null, 'DWH', 'D', 'Getlinked', 'extsrc', '03-JUL-22 11.02.27.000000 AM', '21-JUN-22 06.56.10.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('VPN1', 'Collecting employees VPN logs and activity', 1, null, 'DWH', 'D', 'External files', 'MRR_VPN_LOGS', '06-SEP-20 09.53.54.000000 AM', '13-JAN-22 10.51.32.000000 PM', 'E', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('IB2', 'New IBs dashboard ETL', 1, 'IB', 'DWH4BI', 'D', 'DWH4BI', 'DWH_REP_IB_DASHBOARD', '03-JUL-22 08.15.10.000000 AM', '01-MAY-22 09.00.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MON1', 'Alerts Procedure New', 1, null, 'DWH', 'M', 'DWH_DIM_MONITOR_2', 'DWH_FACT_MONITOR_2', '03-JUL-22 11.45.12.000000 AM', '02-JUL-22 10.36.06.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('REG1', 'Regulation and compliance reports', 1, 'Compliance', 'DWH', 'H', 'DWH4BI', 'DWH_REP_REGULATION', '03-JUL-22 05.47.11.000000 AM', '11-APR-22 06.54.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('VC2', 'Voice center aggregations', 1, 'TELEPHONY', 'EXTSRC', 'H', 'EXTSRC.VC_CALLS', 'extsrc.DWH_FACT_VC_INDICATIONS', '03-JUL-22 11.00.40.000000 AM', '14-MAY-22 10.23.17.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FSQ3', 'Python files loading', 1, 'BI', null, 'H', 'PYTHON', 'DWH.DWH_FACT_FS_QUEUE', '23-MAY-22 01.10.26.000000 PM', '22-MAY-22 12.32.17.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('JR1', 'Jira', 1, 'Jira', 'DWH', 'H', 'Extsrc', 'mgmt_fact_jira_withdraw, mgmt_fact_jira_call_mon', '03-JUL-22 10.54.10.000000 AM', '10-MAY-22 11.46.00.000000 AM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('ONC1', 'Overnight rolling commissions', 1, 'Commissions', 'DWH', 'D', 'Production', 'ONC tables', '03-JUL-22 08.45.21.000000 AM', '26-JUN-22 04.15.41.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MW1', 'Monitoring warnings', 1, 'Monitoring', 'DWH', 'M', 'Jira', 'DWH_REP_COMPLIENCE_WARNINGS', '03-JUL-22 11.40.22.000000 AM', '30-JUN-22 06.11.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('PNL1', 'Users pannels for statistics and prediction', 1, 'PANELS', 'DWH', 'D', 'DWH4BI', 'DWH_FACT_SUBCHANNELS_PERFORMANCE', '24-OCT-19 01.15.56.000000 AM', '18-OCT-19 12.30.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CRM1', 'CRM tickets', 1, 'Users', 'DWH', 'M', 'DWH4BI', 'MGMT_CRM_TICKETS', '03-JUL-22 11.08.20.000000 AM', '18-DEC-21 02.37.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FB1', 'Facebook ad fact', 1, 'Marketing', 'DWH', 'M', 'DWH4BI', 'MGMT_FACT_FACEBOOK_AD', '03-JUL-22 11.30.13.000000 AM', '29-MAY-22 09.04.29.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('UE1', 'User events data from production', 1, 'PRODUCT', 'DWH4BI', 'D', 'DWH4BI', 'DWH_FACT_USER_EVENTS', '03-JUL-22 11.05.00.000000 AM', '03-APR-22 09.22.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('RTS1', 'Retention scores ETL', 1, 'RETENTION', 'DWH', 'D', 'Data warehouse', 'DWH_SCORE_RETENTION', '03-JUL-22 11.24.55.000000 AM', '03-APR-22 10.54.01.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SOD1', 'Start of day data', 0, 'CORE', 'DWH', 'D', 'Paragonex production', 'SOD_USERS_SUMMARY', '14-JAN-21 01.15.04.000000 AM', '03-DEC-19 12.44.42.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('ACC1', 'Accumulated report', 1, 'Finance', 'DWH', 'D', 'DWH4BI', 'DWH_REP_ACCUMULATED_REPORT', '03-JUL-22 04.18.03.000000 AM', '19-DEC-21 02.00.04.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TD1', 'Tracking data mobile web', 0, 'Users', 'DWH', 'H', 'DWH', 'DWH_TD1_TRACKING_DATA', '03-JUL-22 09.19.35.000000 AM', '18-JUN-22 08.08.48.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SES1', 'Sessions dashboard', 1, 'Usage', 'DWH', 'H', 'Production sessions files', 'DWH_REP_SESSIONS', '03-JUL-22 11.38.14.000000 AM', '03-APR-22 02.37.01.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('US4', 'Users monthly aggregations- DR report', 1, null, 'DWH', 'D', 'DWH4BI', 'DWH_REP_DEALING_DASHBOARD_AGG', '02-JUL-22 11.43.41.000000 PM', '14-FEB-22 08.23.12.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FB2', 'Facebook data collection on python', 1, 'Marketing', 'BI', 'H', 'FB API', 'EXTSRC.MRR_FB2', '03-JUL-22 11.26.26.000000 AM', '30-JUN-22 06.20.07.000000 AM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CNV2', 'Conversion bonuses assistance data', 0, 'CONVERSION', 'DWH', 'H', 'DWH', 'DWH_REP_CONVERSION_BONUSES', '17-FEB-21 03.00.02.000000 AM', '31-JAN-21 09.27.16.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MRK3', 'Aggregated tables from Marketing dashboard', 1, 'MARKETING', 'DWH', 'M', 'DWH4BI', 'DWH_REP_MARKETING_DASHBOARD_AGG_SALES', '03-JUL-22 11.13.35.000000 AM', '28-JUN-22 08.48.04.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('ZD1', 'ZenDesk data collection on python', 1, 'Compliance', 'BI', 'H', 'ZenDesk API', 'EXTSRC.MRR_ZD1', '21-APR-22 11.41.45.000000 AM', '06-JUN-22 02.01.28.000000 PM', 'E', to_date('25-03-2021 13:44:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CNT1', 'Users contacts aggregation', 1, 'Marketing', 'DWH4BI', 'D', 'VC_CALLS, SILVERPOP, COMMUNICATION_HISTORY, ZENDESK', 'DWH_FACT_USER_CONTACTS', '08-JUN-22 10.42.36.000000 PM', '16-DEC-21 03.02.39.000000 AM', 'P', to_date('13-06-2021 11:50:31', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('GVT1', 'Google vault export', 1, 'CORE', 'DWH4BI', 'D', 'Google vault', 'EXTSRC', '12-JUN-22 12.26.22.000000 AM', '12-JUN-22 12.48.58.000000 PM', 'R', to_date('14-06-2021 08:46:26', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('GVT2', 'Google vault email body export', 1, 'CORE', 'DWH4BI', 'D', 'Google vault', 'EXTSRC', '04-MAY-22 06.36.25.000000 PM', '04-MAY-22 12.36.06.000000 PM', 'R', to_date('23-06-2021 07:23:02', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('PRD1', 'Product KPIs', 0, 'Product', 'DWH', 'M', 'DWH', 'DWH_REP_PRODUCT_KPIS', '24-NOV-21 12.46.00.000000 PM', '24-NOV-21 11.00.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('KPI', 'HR data for KPI', 0, 'Employee', 'DWH', 'D', 'DWH4BI', 'DWH_KPI', '01-MAR-18 02.34.45.000000 PM', '06-MAY-18 08.04.44.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('PRT1', 'Tables partitioning automation', 1, 'INTERNAL', 'BI', 'D', 'DWH', 'DWH', '02-JUL-22 08.01.44.000000 PM', '26-DEC-21 08.01.57.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('EM2', 'Employee data from Jira', 1, 'Employee', 'DWH', 'D', 'Jira', 'DWH_DIM_EMPLOYEE', '01-JUL-22 02.00.55.000000 AM', '20-DEC-21 02.00.49.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('PERF1', 'Performance data collect on prgn database', 1, 'INTERNAL', 'BI', 'H', 'DWH4BI', 'DWH_FACT_PERFORMANCE_AHS', '03-JUL-22 10.48.09.000000 AM', '10-MAY-22 10.23.42.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('NWD1', 'Users deposits vs declared Net woth', 1, 'COMPLIENCE', 'DWH', 'H', 'DWH4BI', 'DWH_REP_NET_WORTH_DEPOSITS', '03-JUL-22 11.44.24.000000 AM', '03-APR-22 12.58.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SET1', 'Settings table data', 1, 'CORE', 'DWH', 'H', 'DWH4BI', 'DWH_FACT_SETTINGS', '03-JUL-22 10.31.13.000000 AM', '03-APR-22 12.55.50.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('RCH1', 'Rates check report for complience', 0, 'COMPLIANCE', 'DWH', 'D', 'DWH4BI', 'DWH_REP_RATES_CHECK', '26-OCT-21 10.19.33.000000 AM', '26-OCT-21 12.43.28.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CZ3', 'Czech bank automated reports', 1, 'Regulation', 'DWH', 'MON', 'Production', 'Excel files via email', '24-MAY-22 11.28.36.000000 AM', '24-MAY-22 06.48.16.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AT1', 'User AT info parsing', 0, 'USERS', 'DWH', 'M', 'Paragonex', 'AT_INFO_EXTENDED', '12-MAY-20 12.00.20.000000 PM', '19-APR-20 01.00.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('QT1', 'Quotes processing and aggregations', 1, 'Quotes', 'DWH', 'M', 'External quotes source', 'QUOTES_SS', '03-JUL-22 11.00.09.000000 AM', '25-MAY-22 01.00.01.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AB1', 'Account bonuses data', 1, 'Bonuses', 'DWH', 'M', 'DWH4BI', 'MGMT_FACT_ACCOUNT_BONUSES', '27-JUN-22 07.24.00.000000 AM', '03-JUL-22 11.41.01.000000 AM', 'E', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FN1', 'Main financial data - payments , deposits , credits and debits', 1, 'FINANCE', 'DWH', 'M', 'DWH4BI', 'MGMT_FACT_CREDITS_DEBITS , MGMT_FACT_DEPOSITS , MGMT_FACT_PAYMENTS', '03-JUL-22 10.51.49.000000 AM', '02-JUL-22 09.41.53.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('MRK1', 'Marketing related data', 1, 'MARKETING', 'DWH', 'M', 'DWH4BI', 'MGMT_MRR_MKT_EVENTS,MGMT_FACT_LP_DAY_AG,MGMT_USERS_IMP_INFO', '03-JUL-22 11.04.47.000000 AM', '08-MAY-22 12.32.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SALE1', 'Sales data integration', 1, 'SALES', 'DWH', 'M', 'DWH4BI', null, '03-JUL-22 11.12.42.000000 AM', '03-APR-22 09.00.00.000000 AM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('PRJ1', 'Projection data refresh by desk', 0, 'PROJECTION', 'DWH', 'H', 'DWH4BI', 'MGMT_FACT_PROJECTION', '03-OCT-20 10.38.04.000000 PM', null, 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEAL1', 'Dealing room reports', 1, 'DEALING', 'DWH', 'M', 'DWH4BI', null, '03-JUL-22 11.29.51.000000 AM', '29-JUN-22 09.24.40.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CNV1', 'Conversion performance', 1, 'Sales', 'DWH', 'M', 'DWH', null, '02-DEC-21 10.12.47.000000 AM', '02-DEC-21 09.06.01.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('BOU1', 'Back office users process', 1, 'Employee', 'DWH', 'M', 'DWH', 'DWH_DIM_BO_USERS', '03-JUL-22 10.34.05.000000 AM', '16-DEC-21 05.05.29.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('RET1', 'New Retention dashboard ETL', 1, 'SALES', 'DWH', 'M', 'DWH4BI', 'DWH_REP_RETENTION_DASHBOARD', '03-JUL-22 11.38.53.000000 AM', '29-JUN-22 01.54.03.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('EOD1', 'End of day balance table data', 1, 'Core', 'DWH', 'H', 'Production', 'MGMT_MRR_ACCT_EOD_SUMMARY', '03-JUL-22 05.54.19.000000 AM', '14-MAY-22 04.44.50.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('PNT9', 'Point9 daily files', 1, 'Compliance', 'DWH', 'D', 'DWH4BI', 'CSV files on ams-prgn01', '03-JUL-22 01.12.47.000000 AM', '16-DEC-21 01.01.28.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEAL2', 'Dealing room real time dashboard', 0, 'DEALING', 'DWH', 'M', 'DWH4BI', 'Tableau dashboard', '04-FEB-20 09.08.02.000000 AM', '30-JAN-20 04.37.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SU1', 'Surveys data', 1, 'CORE', 'DWH', 'H', 'DWH4BI', 'DWH_FACT_SURVEYS', '03-JUL-22 10.53.01.000000 AM', '16-DEC-21 06.30.14.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AP2', 'Account performance report , replacement of Old BO report', 1, 'FINANCE', 'DWH4BI', 'H', 'DWH4BI', 'DWH_REP_ACCOUNT_PERFORMANCE', '03-JUL-22 06.42.51.000000 AM', '03-JUL-22 04.01.43.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AD2', 'Google Ads Python', 1, null, 'DWH', 'D', 'Google', 'extsrc', '28-JUN-22 07.18.03.000000 PM', '03-JUL-22 11.43.07.000000 AM', 'E', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('RTC1', 'Dealing room Rate change report', 1, 'DEALING', 'DWH', 'D', 'DWH4BI', null, '03-JUL-22 07.25.01.000000 AM', '16-DEC-21 06.43.02.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEAL5', 'Dealing room assets dashboard', 1, 'DEALING', 'DWH4BI', 'M', 'DWH4BI', 'Tableau dashboard', '03-JUL-22 11.42.56.000000 AM', '03-APR-22 12.55.50.000000 PM', 'R', to_date('17-02-2021 11:33:05', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TRS1', 'Google translate users features', 1, 'CORE', 'DWH4BI', 'D', 'mgmt_fact_users', 'dwh_dim_*_translate', '03-JUL-22 11.31.09.000000 AM', '03-APR-22 09.31.05.000000 AM', 'P', to_date('13-07-2021 09:34:10', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CXP1', 'CellXpert Integration', 0, 'IB', 'EXTSRC', 'D', 'CellXpert API', 'MRR_CELLXPERT_*', '16-MAR-22 09.33.23.000000 AM', '27-MAR-22 06.33.06.000000 AM', 'E', to_date('16-08-2021 07:39:45', 'dd-mm-yyyy hh24:mi:ss'));

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FTR2', 'FTR operations alerts', 0, 'PAYMENTS', 'DWH', 'M', 'DWH4BI', 'DWH_REP_OPERATIONS_ALERTS', '12-APR-22 06.02.24.000000 AM', '16-DEC-21 06.58.02.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('USR2', 'MGMT_FACT_USERS history CSD by AUDITING', 0, null, 'DWH', 'D', 'MGMT_FACT_USERS', 'MGMT_FACT_USERS_HIST', '03-JUL-22 10.49.55.000000 AM', '17-MAY-22 08.12.28.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('JR0', 'Jira sources', 1, 'Jira', 'DWH', 'H', 'JiraDB', 'EXTSRC jira tables', '03-JUL-22 11.43.33.000000 AM', '06-JUN-22 10.25.00.000000 AM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('APF1', 'AppsFlyer Pull API Python', 1, null, 'DWH', 'D', 'AppsFlyer', 'extsrc', '03-JUL-22 07.42.03.000000 AM', '15-JAN-22 07.46.26.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('NG1', 'Nagios monitoring', 1, 'Monitoring', 'DWH', 'H', 'Nagios automatic', 'DWH_FACT_NAGIOS_CHECKS', '03-JUL-22 09.33.12.000000 AM', '07-MAY-18 07.16.37.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FSQ1', 'File system queue from platform', 1, 'FILE SYSTEM DATA', 'DWH', 'H', 'Paragonex production', 'EXTERNAL TABLES IN DWH', '14-DEC-21 11.43.34.000000 AM', '28-NOV-21 06.28.20.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AU1', 'Audit data', 1, 'Auditing', 'DWH', 'H', 'Production', 'DWH_FACT_AUDIT', '03-JUL-22 11.36.22.000000 AM', '16-JUN-22 03.05.22.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TC1', 'Trading central data', 1, 'Platform usage', 'DWH', 'H', 'Platform log files FS_QUEUE to dwh.MRR_TC1_TRADING_CENTRAL', 'DWH_FACT_TRADING_CENTRAL', '03-JUL-22 10.45.01.000000 AM', '07-FEB-21 05.28.50.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DRL2', 'Dialer alerts', 1, 'Dialer', 'DWH', 'H', 'DWH', 'DWH_REP_TELEPHONY_ALERTS', null, null, 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('AP1', 'Account performance', 1, 'Finance', 'DWH', 'D', 'DWH', 'Account performance report', '14-OCT-20 03.00.26.000000 AM', '26-AUG-20 05.13.37.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TRD2', 'Tradable instruments for dealing room', 1, 'Dealing', 'DWH', 'M', 'DWH4BI', 'DWH_REP_TRADABLE_INSTRUMENTS', '03-JUL-22 11.22.00.000000 AM', '03-APR-22 01.26.01.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DLR2', 'Telephony data', 1, 'Telephony', 'DWH', 'M', 'Voice center', 'DWH_REP_TELEPHONY_ALERTS', '03-JUL-22 11.45.09.000000 AM', '07-FEB-22 10.22.13.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('BIM1', 'dwh4bi Monitor Tables', 1, 'BI', 'DWH', 'D', 'DWH4BI', null, null, '15-MAY-22 11.53.49.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('GST1', 'Ghost users analysis and behavior', 1, 'PRODUCT', 'DWH', 'D', 'DWH4BI', 'DWH_REP_GHOST_USERS', null, '05-FEB-21 11.20.44.000000 PM', 'E', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('WD1', 'Withdrawals related data', 0, 'CORE', 'DWH4BI', 'H', 'DWH4BI', 'DWH_FACT_WITHDRAWALS', '15-DEC-21 12.55.00.000000 PM', '21-FEB-22 03.36.16.000000 PM', 'E', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DEAL4', 'Dealing room trends dashboard', 1, 'DEALING', 'DWH4BI', 'M', 'DWH4BI', 'Tableau dashboard', '03-JUL-22 11.42.54.000000 AM', '03-APR-22 12.55.50.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('DLR3', 'Dialer alerts', 1, 'TELEPHONY', 'DWH4BI', 'M', 'EXTSRC.VC_CALLS', 'DWH_REP_DIALER_ALERTS_PROVIDER', '03-JUL-22 11.31.31.000000 AM', '05-MAR-22 06.38.36.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('SW1', 'Sales related warnings', 1, 'SALES', 'DWH4BI', 'M', 'DWH4BI', 'DWH_ALERT_50K_BALANCE_ALERTS', '03-JUL-22 11.42.21.000000 AM', '03-APR-22 12.55.50.000000 PM', 'R', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('EOD2', 'BI internal EOD', 1, null, 'DWH', 'H', null, 'DWH_FACT_EOD', '03-JUL-22 01.16.02.000000 AM', '25-MAY-22 07.49.33.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('FRD1', 'Fraud users report', 1, 'MARKETING', 'DWH', 'H', 'DWH4BI', 'DWH_REP_FRAUD_USERS', '03-JUL-22 11.15.54.000000 AM', '18-DEC-21 01.17.00.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('TO1', 'Trade out user events monitor', 1, 'SALES', 'DWH4BI', 'H', 'DWH4BI', 'DWH_REP_TRADE_OUT', '03-JUL-22 11.13.00.000000 AM', '23-FEB-22 08.25.00.000000 AM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('BOB1', 'Betobet dashboard', 1, 'Betobet', 'DWH', 'H', 'Production', 'DWH_REP_BETOBET_DASHBOARD', '03-JUL-22 01.00.56.000000 AM', '17-JAN-22 12.57.36.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CZ4', 'Czech regulation daily reports 1Market', 1, 'Regulation', 'DWH', 'D', 'Production', 'Excel files via email', '03-JUL-22 02.01.46.000000 AM', '01-MAY-22 12.55.26.000000 PM', 'P', null);

insert into DWH_DIM_PROCESSES (PROCESS_NAME, PROCESS_DESCRIPTION, PROCESS_STATUS, PROCESS_CATEGORY, PROCESS_OWNER, PROCESS_SCHEDULE, SOURCE_DESCRIPTION, TARGET_DESCRIPTION, LAST_FINISHED_DATE, LAST_ERROR_DATE, EXECUTION_STATUS, BI_UPDATE_DATE)
values ('CZ5', 'Czech bank automated reports 1Market', 1, 'Regulation', 'DWH', 'MON', 'Production', 'Excel files via email', '09-JUN-22 01.08.27.000000 PM', '24-MAY-22 12.47.36.000000 PM', 'P', null);

prompt Done.
