insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', -1, 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', -1, 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 77, 'Crowd Tech', 'Saxo', 'Saxo', '#', 'STP', ' ', ' ', ' ', 5);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 77, 'Crowd Tech', 'Saxo', 'Saxo', '#', 'STP', ' ', ' ', ' ', 5);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 7, 'Reliantco', 'Reliantco Investments Ltd', 'Reliantco Investments Ltd', 'ID 4', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 7, 'Reliantco', 'Sirius Financial Markets PTY Ltd – Client ID 1', 'Sirius Financial Markets PTY Ltd', 'ID 4', 'Market Maker', 'Reliantco Investments Ltd', 'ID 1 - 270726', 'STP', 4);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 77, 'Crowd Tech', 'Crowd Tech Ltd', 'Crowd Tech Ltd', 'ID 6', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 77, 'Crowd Tech', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID 6', 'Market Maker', 'Crowd Tech Ltd', 'ID 1 - 297365', 'STP', 1);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 77, 'Crowd Tech', 'Sirius Financial Markets PTY Ltd – Client ID 1', 'Sirius Financial Markets PTY Ltd', 'ID 6', 'Market Maker', 'Crowd Tech Ltd', 'ID 1 - 297365', 'STP', 4);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 7, 'UFX Global', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID 5', 'Market Maker', 'UFX Global LTD.', 'ID 1 - 136450', 'STP', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 7, 'UFX Global', 'UFX Global LTD.', 'UFX Global LTD.', 'ID 5', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 77, 'ST Services', 'ST Services Ltd', 'ST Services Ltd', 'ID X', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 47, 'ST Services', 'ST Services Ltd', 'ST Services Ltd', 'ID X', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 77, 'ST Services', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID X', 'Market Maker', 'ST Services Ltd', 'ID X', 'STP', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 47, 'ST Services', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID X', 'Market Maker', 'ST Services Ltd', 'ID X', 'STP', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('OPEN', 27, 'Exelcius Prime Limited', 'Exelcius Prime Limited', 'Exelcius Prime Limited', 'ID X', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 7, 'Reliantco', 'Reliantco Investments Ltd', 'Reliantco Investments Ltd', 'ID 4', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 7, 'Reliantco', 'Sirius Financial Markets PTY Ltd – Client ID 1', 'Sirius Financial Markets PTY Ltd', 'ID 4', 'Market Maker', 'Reliantco Investments Ltd', 'ID 1 - 270726', 'STP', 4);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 77, 'Crowd Tech', 'Crowd Tech Ltd', 'Crowd Tech Ltd', 'ID 6', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 77, 'Crowd Tech', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID 6', 'Market Maker', 'Crowd Tech Ltd', 'ID 1 - 297365', 'STP', 1);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 77, 'Crowd Tech', 'Sirius Financial Markets PTY Ltd – Client ID 1', 'Sirius Financial Markets PTY Ltd', 'ID 6', 'Market Maker', 'Crowd Tech Ltd', 'ID 1 - 297365', 'STP', 4);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 7, 'UFX Global', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID 5', 'Market Maker', 'UFX Global LTD.', 'ID 1 - 136450', 'STP', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 7, 'UFX Global', 'UFX Global LTD.', 'UFX Global LTD.', 'ID 5', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 77, 'ST Services', 'ST Services Ltd', 'ST Services Ltd', 'ID X', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 47, 'ST Services', 'ST Services Ltd', 'ST Services Ltd', 'ID X', 'STP', ' ', ' ', ' ', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 77, 'ST Services', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID X', 'Market Maker', 'ST Services Ltd', 'ID X', 'STP', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 47, 'ST Services', 'PX EXCHANGE LTD. – Client ID 1', 'PX EXCHANGE LTD.', 'ID X', 'Market Maker', 'ST Services Ltd', 'ID X', 'STP', 0);

insert into DWH_DIM_POSITIONS_REP_PARAMETERS (REPORT_TYPE, PARTNER_ID, COMPANY_NAME, ACCOUNT_STATEMENT, ACCOUNT_HOLDER, ACCOUNT_NUMBER, ACCOUNT_STATUS, SUB_ACCOUNT_HOLDER, SUB_ACCOUNT_NUMBER, SUB_ACCOUNT_STATUS, LIQUIDITY_PROVIDER)
values ('CLOSE', 27, 'Exelcius Prime Limited', 'Exelcius Prime Limited', 'Exelcius Prime Limited', 'ID X', 'STP', ' ', ' ', ' ', 0);

